spring:
  datasource:
    url: # url of Postgres ${datasource-url}
    username: # Username of Postgres ${datasource-username}
    password: # Pass of postgres ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: none # Data definition language auto generation
